#!/bin/bash
#
# Easy way to create a symfony2 project 
# USE:  sudo  ./pathtoscript/createpj projectname
# Author: Alejandro hurtado <ahurt2000@gmail.com>
#

SCRIPTPATH=`dirname "$(readlink -f $0)"`
source $SCRIPTPATH/config

#create vhost (In ubuntu) 
sudo $SCRIPTPATH/vhostcreate $1 $EXT $MYPRJ

#hosts file
if ! $SCRIPTPATH/hostexist $1.$EXT; then
  echo "*** host $1.$EXT added to the hosts file ***"
  sudo bash  -c "echo -e '${SERVERIP}\t${1}.$EXT'>>/etc/hosts"
fi

#download and prepare 
wget http://symfony.com/download?v=Symfony_Standard_$SF2VERSION.tgz -O temp_sf2.tgz
tar -C $MYPRJ -xf temp_sf2.tgz 
rm temp_sf2.tgz
mv $MYPRJ/Symfony $MYPRJ/$1

#the putacl script  
#cp $SCRIPTPATH/putacl $MYPRJ/$1/
$SCRIPTPATH/putacl $USER $MYPRJ/$1/

sudo a2ensite $1.site

echo -e '\E[32;40m'
echo "Your next steps:"
echo -e "\033[1mcd  $MYPRJ/$1/; php bin/vendors install\033[0m"
echo -e "Point your browser to \033[4mhttp://$1.local/web/config\033[0m to start "
tput sgr0
echo
exit 0
