#!/bin/bash
# Script: get the mount point in fstab for a folder path
# USE: getmountpoint FOLDERPATH

MOUNTPOINT=""
#MOUNTPOINTS=$(cat /etc/fstab |grep -v "^#"|awk '{print $2}')
for line in `cat /etc/fstab |grep -v "^#"|awk '{print $2}'`; do
   if [[ $1 == *$line*  ]];then
	if [ "${#line}" -gt "${#MOUNTPOINT}" ];then
	   MOUNTPOINT=$line
	fi
   fi
done
echo $MOUNTPOINT
exit 0
